[package]
name = "vote-commitment-tree"
version = "0.4.0-rc.1"
edition = "2021"
description = "Append-only Poseidon Merkle tree for Vote Authority Notes and Vote Commitments in the Zcash shielded-voting protocol."
license = "MIT OR Apache-2.0"
repository = "https://github.com/valargroup/zcash_voting"
readme = "README.md"

[dependencies]
imt-tree = "=0.2.0"
pasta_curves = "0.5"
ff = "0.13"
halo2_gadgets = { version = "=0.5.0", default-features = false }
anyhow = "1.0"
incrementalmerkletree = "0.8.1"
shardtree = "0.7"
lazy_static = "1"
libc = "0.2"

[dev-dependencies]
rand = "0.8"
orchard = { workspace = true }
voting-circuits = { workspace = true }
